# Generated by Django 4.2.6 on 2023-10-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneygroove', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_savings',
            field=models.IntegerField(default=0),
        ),
    ]
